export {
  api,
  submitAdvisory,
  submitAdvisoryWithPhoto,
  getHealth,
  registerFarmer,
  getFarmerProfile,
  getAuditRecord,
  getFarmerAdvisories,
  getSchemes,
  speechToText,
  textToSpeech,
  getMandiPrices,
  getMSPList,
  getAvailableStates,
  getAvailableCrops,
  getWeatherForecast,
  getCurrentWeather,
} from './api';
